You are a data analyst working for a tech company closely monitoring the AI tools market. You want to understand the evolving popularity of three major AI tools, ChatGPT, Gemini, and Microsoft Copilot, and identify which tool is gaining the most traction and how they compare over time.


<img src="ai_tools.jpg" align="center"/>

You'll work with real-world time series data that captures the global interest in these tools over several weeks. Your goal is to analyze this data, uncover patterns, and provide actionable insights to help your company make informed decisions. This might include determining where to focus marketing efforts, predicting future trends, or identifying potential areas for improvement.

Are you ready to help your company stay ahead of the curve in the competitive AI tools market? Let's get started!

### The Data

The Google Trends data is available as a CSV file `ai_tools_comparison.csv`.
The data contains the number of worldwide searches for chatGpt, Gemini, and Microsoft Copilot over the past 12 months as of September 2024. 
<!--- Link to query: https://trends.google.com/trends/explore?q=chatgpt,gemini,%2Fg%2F11tsqm45vd&hl=en-US -->

In [1]:
import pandas as pd
import matplotlib.pyplot as plt

# Load the data
trends = pd.read_csv('ai_tools_comparison.csv')

# Inspect the data
trends.head()

         week  chatgpt  gemini  microsoft_copilot
0  2023-08-27       56       3                  1
1  2023-09-03       56       3                  1
2  2023-09-10       63       3                  1
3  2023-09-17       64       3                  1
4  2023-09-24       66       3                  1

In [2]:
# Start coding here
# Use as many cells as you need
import seaborn as sns

In [3]:
trends['chatgpt'].pct_change().rolling(window=3).mean()#14

0          NaN
1          NaN
2          NaN
3     0.046958
4     0.057374
5     0.020758
6     0.020442
7     0.014928
8     0.019539
9     0.005174
10    0.029258
11    0.001818
12    0.029987
13    0.023224
14    0.036835
15    0.013836
16   -0.076762
17   -0.153241
18   -0.085191
19    0.048661
20    0.119356
21    0.055526
22    0.005434
23    0.034992
24    0.034992
25    0.019608
26    0.023148
27    0.023148
28    0.010161
29    0.005031
30   -0.033431
31    0.003711
32   -0.009802
33    0.064215
34    0.040060
35    0.031539
36   -0.020276
37    0.031006
38    0.035022
39    0.040171
40    0.023372
41   -0.028712
42   -0.046407
43   -0.089899
44   -0.056334
45   -0.042233
46   -0.028096
47   -0.004527
48    0.015154
49    0.044339
50    0.065956
51    0.089787
52    0.100928
53   -0.002406
Name: chatgpt, dtype: float64

In [4]:
trends['gemini'].pct_change().rolling(window=3).mean()#16

0          NaN
1          NaN
2          NaN
3     0.000000
4     0.000000
5     0.000000
6     0.111111
7     0.111111
8     0.111111
9    -0.083333
10   -0.083333
11   -0.083333
12    0.000000
13    0.000000
14    0.777778
15    0.711111
16    0.627778
17   -0.205556
18   -0.138889
19   -0.122222
20   -0.066667
21   -0.066667
22    0.000000
23    0.250000
24    0.488095
25    0.571429
26    0.321429
27    0.038889
28   -0.044444
29   -0.018803
30   -0.021978
31   -0.021978
32   -0.047619
33    0.055556
34    0.055556
35    0.055556
36    0.023810
37    0.046032
38    0.066865
39    0.023448
40    0.022059
41   -0.037990
42   -0.018382
43   -0.061438
44   -0.046032
45   -0.071673
46   -0.021673
47    0.002137
48    0.027778
49    0.025641
50    0.025641
51    0.049451
52    0.046032
53    0.004365
Name: gemini, dtype: float64

In [5]:
trends['microsoft_copilot'].pct_change().rolling(window=3).mean()#8

0          NaN
1          NaN
2          NaN
3     0.000000
4     0.000000
5     0.000000
6     0.000000
7     0.000000
8     0.333333
9     0.333333
10    0.333333
11    0.000000
12    0.166667
13    0.055556
14    0.222222
15    0.055556
16    0.055556
17   -0.111111
18    0.055556
19    0.166667
20    0.277778
21    0.111111
22    0.111111
23    0.000000
24    0.166667
25    0.111111
26    0.177778
27    0.011111
28    0.066667
29    0.000000
30    0.000000
31    0.000000
32    0.000000
33    0.000000
34    0.000000
35   -0.111111
36   -0.111111
37   -0.027778
38    0.150000
39    0.094444
40    0.011111
41   -0.055556
42    0.000000
43   -0.066667
44   -0.066667
45   -0.150000
46    0.027778
47    0.027778
48    0.027778
49    0.027778
50    0.027778
51    0.111111
52    0.083333
53   -0.050000
Name: microsoft_copilot, dtype: float64

In [6]:
most_consistent_tool = "chatgpt"

          week  chatgpt  gemini  microsoft_copilot
0   2023-08-27       56       3                  1
1   2023-09-03       56       3                  1
2   2023-09-10       63       3                  1
3   2023-09-17       64       3                  1
4   2023-09-24       66       3                  1
5   2023-10-01       67       3                  1
6   2023-10-08       68       4                  1
7   2023-10-15       69       4                  1
8   2023-10-22       71       4                  2
9   2023-10-29       69       3                  2
10  2023-11-05       75       3                  2
11  2023-11-12       71       3                  2
12  2023-11-19       75       3                  3
13  2023-11-26       80       3                  2
14  2023-12-03       79      10                  3
15  2023-12-10       78       8                  3
16  2023-12-17       62       6                  2
17  2023-12-24       47       5                  2
18  2023-12-31       56       5                  3
19  2024-01-07       67       4                  3
20  2024-01-14       65       4                  4
21  2024-01-21       65       4                  4
22  2024-01-28       68       4                  4
23  2024-02-04       72       7                  4
24  2024-02-11       72      12                  6
25  2024-02-18       72      15                  5
26  2024-02-25       77      15                  6
27  2024-03-03       77      13                  6
28  2024-03-10       74      13                  6
29  2024-03-17       78      14                  6
30  2024-03-24       69      12                  6
31  2024-03-31       74      12                  6
32  2024-04-07       75      12                  6
33  2024-04-14       83      14                  6
34  2024-04-21       83      14                  6
35  2024-04-28       82      14                  4
36  2024-05-05       78      15                  4
37  2024-05-12       90      16                  5
38  2024-05-19       90      17                  6
39  2024-05-26       87      16                  5
40  2024-06-02       96      17                  5
41  2024-06-09       81      15                  5
42  2024-06-16       74      15                  5
43  2024-06-23       72      14                  4
44  2024-06-30       68      13                  4
45  2024-07-07       65      12                  3
46  2024-07-14       66      13                  4
47  2024-07-21       67      13                  4
48  2024-07-28       68      13                  3
49  2024-08-04       75      14                  4
50  2024-08-11       81      14                  4
51  2024-08-18       88      15                  4
52  2024-08-25      100      16                  5
53  2024-09-01       77      14                  3

In [8]:
gpt_dip = "December 2023"

In [9]:
trends.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54 entries, 0 to 53
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   week               54 non-null     object
 1   chatgpt            54 non-null     int64
 2   gemini             54 non-null     int64
 3   microsoft_copilot  54 non-null     int64
dtypes: int64(3), object(1)
memory usage: 1.8+ KB

In [10]:
trends['week'] = pd.to_datetime(trends['week'])

In [11]:
trends.set_index('week',drop=True)

            chatgpt  gemini  microsoft_copilot
week
2023-08-27       56       3                  1
2023-09-03       56       3                  1
2023-09-10       63       3                  1
2023-09-17       64       3                  1
2023-09-24       66       3                  1
2023-10-01       67       3                  1
2023-10-08       68       4                  1
2023-10-15       69       4                  1
2023-10-22       71       4                  2
2023-10-29       69       3                  2
2023-11-05       75       3                  2
2023-11-12       71       3                  2
2023-11-19       75       3                  3
2023-11-26       80       3                  2
2023-12-03       79      10                  3
2023-12-10       78       8                  3
2023-12-17       62       6                  2
2023-12-24       47       5                  2
2023-12-31       56       5                  3
2024-01-07       67       4                  3
2024-01-14       65       4                  4
2024-01-21       65       4                  4
2024-01-28       68       4                  4
2024-02-04       72       7                  4
2024-02-11       72      12                  6
2024-02-18       72      15                  5
2024-02-25       77      15                  6
2024-03-03       77      13                  6
2024-03-10       74      13                  6
2024-03-17       78      14                  6
2024-03-24       69      12                  6
2024-03-31       74      12                  6
2024-04-07       75      12                  6
2024-04-14       83      14                  6
2024-04-21       83      14                  6
2024-04-28       82      14                  4
2024-05-05       78      15                  4
2024-05-12       90      16                  5
2024-05-19       90      17                  6
2024-05-26       87      16                  5
2024-06-02       96      17                  5
2024-06-09       81      15                  5
2024-06-16       74      15                  5
2024-06-23       72      14                  4
2024-06-30       68      13                  4
2024-07-07       65      12                  3
2024-07-14       66      13                  4
2024-07-21       67      13                  4
2024-07-28       68      13                  3
2024-08-04       75      14                  4
2024-08-11       81      14                  4
2024-08-18       88      15                  4
2024-08-25      100      16                  5
2024-09-01       77      14                  3

In [12]:
trends.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54 entries, 0 to 53
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   week               54 non-null     datetime64[ns]
 1   chatgpt            54 non-null     int64
 2   gemini             54 non-null     int64
 3   microsoft_copilot  54 non-null     int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 1.8 KB

In [13]:
trends.head()

        week  chatgpt  gemini  microsoft_copilot
0 2023-08-27       56       3                  1
1 2023-09-03       56       3                  1
2 2023-09-10       63       3                  1
3 2023-09-17       64       3                  1
4 2023-09-24       66       3                  1

In [14]:
trends.set_index('week',drop=True,inplace=True)

In [15]:

monthly = trends.resample('M').mean()

In [16]:
print(monthly)

            chatgpt  gemini  microsoft_copilot
week
2023-08-31    56.00    3.00               1.00
2023-09-30    62.25    3.00               1.00
2023-10-31    68.80    3.60               1.40
2023-11-30    75.25    3.00               2.25
2023-12-31    64.40    6.80               2.60
2024-01-31    66.25    4.00               3.75
2024-02-29    73.25   12.25               5.25
2024-03-31    74.40   12.80               6.00
2024-04-30    80.75   13.50               5.50
2024-05-31    86.25   16.00               5.00
2024-06-30    78.20   14.80               4.60
2024-07-31    66.50   12.75               3.50
2024-08-31    86.00   14.75               4.25
2024-09-30    77.00   14.00               3.00

In [17]:
best_month = "May"