In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import requests

Visual Crossing - Weather API

In [2]:
from google.colab import userdata
weather_token = userdata.get('weather_token')

In [3]:
df_weather = pd.read_csv(f"https://weather.visualcrossing.com/VisualCrossingWebServices/rest/services/retrievebulkdataset?&key={weather_token}&taskId=1b33ab32aaca5575980ce5c3cc98f0d0&zip=false")

In [4]:
df_weather.head()

,name,datetime,tempmax,tempmin,temp,feelslikemax,feelslikemin,feelslike,dew,humidity,...,solarenergy,uvindex,severerisk,sunrise,sunset,moonphase,conditions,description,icon,stations
0,New York City,2016-01-01,42.5,35.1,39.4,38.2,26.4,33.0,23.7,53.2,...,8.1,4,NaN,2016-01-01T07:20:07,2016-01-01T16:38:54,0.73,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,"72505394728,KEWR,KLGA,72502014734,KNYC,7250301..."
1,New York City,2016-01-02,39.8,33.2,36.0,36.4,24.7,29.7,18.2,48.0,...,9.2,4,NaN,2016-01-02T07:20:13,2016-01-02T16:39:45,0.75,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,"72505394728,KEWR,KLGA,72502014734,KNYC,7250301..."
2,New York City,2016-01-03,45.0,34.9,38.9,39.4,27.6,32.8,21.4,49.5,...,8.9,4,NaN,2016-01-03T07:20:17,2016-01-03T16:40:37,0.80,Clear,Clear conditions throughout the day.,clear-day,"72505394728,KEWR,KLGA,72502014734,KNYC,7250301..."
3,New York City,2016-01-04,36.3,15.4,27.9,30.2,-0.4,17.3,9.9,47.0,...,7.8,4,NaN,2016-01-04T07:20:19,2016-01-04T16:41:30,0.83,Partially cloudy,Clearing in the afternoon.,partly-cloudy-day,"72505394728,KEWR,KLGA,72502014734,KNYC,7250301..."
4,New York City,2016-01-05,28.8,11.7,20.6,28.8,-4.7,12.2,-1.3,39.8,...,9.9,5,NaN,2016-01-05T07:20:19,2016-01-05T16:42:25,0.86,Clear,Clear conditions throughout the day.,clear-day,"72505394728,KEWR,KLGA,72502014734,KNYC,7250301..."

In [5]:
df_weather.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 366 entries, 0 to 365
Data columns (total 33 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   name              366 non-null    object
 1   datetime          366 non-null    object
 2   tempmax           366 non-null    float64
 3   tempmin           366 non-null    float64
 4   temp              366 non-null    float64
 5   feelslikemax      366 non-null    float64
 6   feelslikemin      366 non-null    float64
 7   feelslike         366 non-null    float64
 8   dew               366 non-null    float64
 9   humidity          366 non-null    float64
 10  precip            366 non-null    float64
 11  precipprob        366 non-null    int64
 12  precipcover       366 non-null    float64
 13  preciptype        151 non-null    object
 14  snow              366 non-null    float64
 15  snowdepth         366 non-null    float64
 16  windgust          366 non-null    float64
 17  windspeed         366 non-null    float64
 18  winddir           366 non-null    float64
 19  sealevelpressure  366 non-null    float64
 20  cloudcover        366 non-null    float64
 21  visibility        366 non-null    float64
 22  solarradiation    366 non-null    float64
 23  solarenergy       366 non-null    float64
 24  uvindex           366 non-null    int64
 25  severerisk        0 non-null      float64
 26  sunrise           366 non-null    object
 27  sunset            366 non-null    object
 28  moonphase         366 non-null    float64
 29  conditions        366 non-null    object
 30  description       366 non-null    object
 31  icon              366 non-null    object
 32  stations          366 non-null    object
dtypes: float64(22), int64(2), object(9)
memory usage: 94.5+ KB

In [6]:
df_weather['datetime'] = pd.to_datetime(df_weather['datetime'])

In [33]:
#df_weather.drop(df_weather.columns[[5,6,11,18,22,23,24,25,26,27,28,31,32]], inplace=True,axis=1)
df_weather.drop('description', inplace=True, axis=1)
df_weather.head()

,name,datetime,tempmax,tempmin,temp,feelslike,dew,humidity,precip,precipcover,preciptype,snow,snowdepth,windgust,windspeed,sealevelpressure,cloudcover,visibility,conditions
0,New York City,2016-01-01,42.5,35.1,39.4,33.0,23.7,53.2,0.0,0.0,NaN,0.0,0.0,27.3,14.5,1016.9,71.7,9.9,Partially cloudy
1,New York City,2016-01-02,39.8,33.2,36.0,29.7,18.2,48.0,0.0,0.0,NaN,0.0,0.0,24.8,14.3,1016.8,43.0,9.9,Partially cloudy
2,New York City,2016-01-03,45.0,34.9,38.9,32.8,21.4,49.5,0.0,0.0,NaN,0.0,0.0,26.2,16.8,1011.2,19.8,9.9,Clear
3,New York City,2016-01-04,36.3,15.4,27.9,17.3,9.9,47.0,0.0,0.0,NaN,0.0,0.0,32.0,22.6,1017.7,42.8,9.9,Partially cloudy
4,New York City,2016-01-05,28.8,11.7,20.6,12.2,-1.3,39.8,0.0,0.0,NaN,0.0,0.0,27.9,16.5,1034.5,3.9,9.9,Clear

Open Data NYC - Automated Traffic Data

In [8]:
df_traffic = pd.read_csv("/content/Automated_Traffic_Volume_Counts_2016.csv")

In [9]:
df_traffic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 129617 entries, 0 to 129616
Data columns (total 12 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   RequestID  129617 non-null  int64
 1   Boro       129617 non-null  object
 2   Yr         129617 non-null  int64
 3   M          129617 non-null  int64
 4   D          129617 non-null  int64
 5   Vol        129617 non-null  object
 6   SegmentID  129617 non-null  int64
 7   WktGeom    129617 non-null  object
 8   street     129617 non-null  object
 9   fromSt     129617 non-null  object
 10  toSt       129617 non-null  object
 11  Direction  129617 non-null  object
dtypes: int64(5), object(7)
memory usage: 11.9+ MB

In [10]:
df_traffic.head()

,RequestID,Boro,Yr,M,D,Vol,SegmentID,WktGeom,street,fromSt,toSt,Direction
0,25058,Brooklyn,2016,12,23,11,44587,POINT (1003253.3609464553 196058.4661543698),MORGAN AVENUE,Rock Street,Thames Street,NB
1,25058,Brooklyn,2016,12,23,14,44587,POINT (1003253.3609464553 196058.4661543698),MORGAN AVENUE,Rock Street,Thames Street,NB
2,25058,Queens,2016,12,23,26,81629,POINT (1021107.3457805195 208483.04321635456),54 AVENUE,94 Street,Junction Boulevard,EB
3,25058,Queens,2016,12,23,29,81629,POINT (1021107.3457805195 208483.04321635456),54 AVENUE,94 Street,Junction Boulevard,EB
4,25058,Queens,2016,12,23,24,81629,POINT (1021107.3457805195 208483.04321635456),54 AVENUE,94 Street,Junction Boulevard,EB

In [11]:
df_traffic['Vol'] = pd.to_numeric(df_traffic['Vol'].astype(str).str.replace(',', '', regex=True))

In [12]:
df_traffic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 129617 entries, 0 to 129616
Data columns (total 12 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   RequestID  129617 non-null  int64
 1   Boro       129617 non-null  object
 2   Yr         129617 non-null  int64
 3   M          129617 non-null  int64
 4   D          129617 non-null  int64
 5   Vol        129617 non-null  int64
 6   SegmentID  129617 non-null  int64
 7   WktGeom    129617 non-null  object
 8   street     129617 non-null  object
 9   fromSt     129617 non-null  object
 10  toSt       129617 non-null  object
 11  Direction  129617 non-null  object
dtypes: int64(6), object(6)
memory usage: 11.9+ MB

In [13]:
df_traffic[df_traffic['Vol'].isna() ]

Empty DataFrame
Columns: [RequestID, Boro, Yr, M, D, Vol, SegmentID, WktGeom, street, fromSt, toSt, Direction]
Index: []

In [14]:
df_traffic['datetime'] = pd.to_datetime(df_traffic[['Yr', 'M', 'D']].rename(columns={'Yr': 'year', 'M': 'month', 'D': 'day'}))

df_traffic['datetime']

0        2016-12-23
1        2016-12-23
2        2016-12-23
3        2016-12-23
4        2016-12-23
            ...
129612   2016-01-04
129613   2016-01-04
129614   2016-01-04
129615   2016-01-04
129616   2016-01-04
Name: datetime, Length: 129617, dtype: datetime64[ns]

In [15]:
df_traffic.head()

,RequestID,Boro,Yr,M,D,Vol,SegmentID,WktGeom,street,fromSt,toSt,Direction,datetime
0,25058,Brooklyn,2016,12,23,11,44587,POINT (1003253.3609464553 196058.4661543698),MORGAN AVENUE,Rock Street,Thames Street,NB,2016-12-23
1,25058,Brooklyn,2016,12,23,14,44587,POINT (1003253.3609464553 196058.4661543698),MORGAN AVENUE,Rock Street,Thames Street,NB,2016-12-23
2,25058,Queens,2016,12,23,26,81629,POINT (1021107.3457805195 208483.04321635456),54 AVENUE,94 Street,Junction Boulevard,EB,2016-12-23
3,25058,Queens,2016,12,23,29,81629,POINT (1021107.3457805195 208483.04321635456),54 AVENUE,94 Street,Junction Boulevard,EB,2016-12-23
4,25058,Queens,2016,12,23,24,81629,POINT (1021107.3457805195 208483.04321635456),54 AVENUE,94 Street,Junction Boulevard,EB,2016-12-23

In [16]:
df_traffic_new = df_traffic.drop(columns=['Yr', 'M', 'D'])

In [17]:
df_traffic_new.head()

,RequestID,Boro,Vol,SegmentID,WktGeom,street,fromSt,toSt,Direction,datetime
0,25058,Brooklyn,11,44587,POINT (1003253.3609464553 196058.4661543698),MORGAN AVENUE,Rock Street,Thames Street,NB,2016-12-23
1,25058,Brooklyn,14,44587,POINT (1003253.3609464553 196058.4661543698),MORGAN AVENUE,Rock Street,Thames Street,NB,2016-12-23
2,25058,Queens,26,81629,POINT (1021107.3457805195 208483.04321635456),54 AVENUE,94 Street,Junction Boulevard,EB,2016-12-23
3,25058,Queens,29,81629,POINT (1021107.3457805195 208483.04321635456),54 AVENUE,94 Street,Junction Boulevard,EB,2016-12-23
4,25058,Queens,24,81629,POINT (1021107.3457805195 208483.04321635456),54 AVENUE,94 Street,Junction Boulevard,EB,2016-12-23

In [18]:
# Group by date and borough and sum the volume
daily_df_bor = df_traffic_new.groupby(['datetime','Boro','WktGeom'])['Vol'].sum().reset_index()

In [19]:
daily_df_bor.head()

    datetime   Boro                                        WktGeom    Vol
0 2016-01-04  Bronx   POINT (1003371.099822495 237805.79939774555)  14035
1 2016-01-04  Bronx   POINT (1003577.8879040143 237646.9785419739)   2377
2 2016-01-04  Bronx   POINT (1003618.536844137 237878.89542973498)   3957
3 2016-01-04  Bronx  POINT (1003777.9857996657 237726.06642686282)  11718
4 2016-01-05  Bronx   POINT (1003371.099822495 237805.79939774555)  14593

In [37]:
daily_df_boro = df_traffic_new.groupby(['datetime', 'Boro'])['Vol'].sum().reset_index()

In [38]:
daily_df_boro.head()

    datetime       Boro    Vol
0 2016-01-04      Bronx  32087
1 2016-01-05      Bronx  33827
2 2016-01-06      Bronx   8710
3 2016-01-06  Manhattan  27798
4 2016-01-07      Bronx   8407

In [39]:
daily_df_bor['Boro'].value_counts(normalize=True)

Boro
Brooklyn         0.357045
Queens           0.273598
Bronx            0.168263
Staten Island    0.108755
Manhattan        0.092339
Name: proportion, dtype: float64

In [20]:
daily_df_bor.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1462 entries, 0 to 1461
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   datetime  1462 non-null   datetime64[ns]
 1   Boro      1462 non-null   object
 2   WktGeom   1462 non-null   object
 3   Vol       1462 non-null   int64
dtypes: datetime64[ns](1), int64(1), object(2)
memory usage: 45.8+ KB

In [21]:
daily_df = df_traffic_new.groupby('datetime')['Vol'].sum().reset_index()

In [22]:
daily_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 342 entries, 0 to 341
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   datetime  342 non-null    datetime64[ns]
 1   Vol       342 non-null    int64
dtypes: datetime64[ns](1), int64(1)
memory usage: 5.5 KB

In [23]:
daily_df.head(30)

     datetime    Vol
0  2016-01-04  32087
1  2016-01-05  33827
2  2016-01-06  36508
3  2016-01-07  35449
4  2016-01-08  37139
5  2016-01-09  35907
6  2016-01-10  29314
7  2016-01-11  42911
8  2016-01-12  54047
9  2016-01-13  54295
10 2016-01-14  57349
11 2016-01-15  61613
12 2016-01-16  58407
13 2016-01-17  49739
14 2016-01-18  23549
15 2016-01-19  27753
16 2016-01-20  45147
17 2016-01-21  48119
18 2016-01-22  12272
19 2016-01-30  17897
20 2016-01-31  17426
21 2016-02-01  28091
22 2016-02-02  34511
23 2016-02-03  32850
24 2016-02-04  35366
25 2016-02-05  31686
26 2016-02-06  31227
27 2016-02-07  25087
28 2016-02-08  56283
29 2016-02-09  59538

In [40]:
merged_df = pd.merge(daily_df_boro, df_weather, left_on='datetime', right_on='datetime', how='inner')

In [41]:
merged_df.head()

,datetime,Boro,Vol,name,tempmax,tempmin,temp,feelslike,dew,humidity,...,precipcover,preciptype,snow,snowdepth,windgust,windspeed,sealevelpressure,cloudcover,visibility,conditions
0,2016-01-04,Bronx,32087,New York City,36.3,15.4,27.9,17.3,9.9,47.0,...,0.0,NaN,0.0,0.0,32.0,22.6,1017.7,42.8,9.9,Partially cloudy
1,2016-01-05,Bronx,33827,New York City,28.8,11.7,20.6,12.2,-1.3,39.8,...,0.0,NaN,0.0,0.0,27.9,16.5,1034.5,3.9,9.9,Clear
2,2016-01-06,Bronx,8710,New York City,40.4,24.8,32.4,29.2,5.0,32.4,...,0.0,NaN,0.0,0.0,15.0,8.5,1033.3,4.7,9.9,Clear
3,2016-01-06,Manhattan,27798,New York City,40.4,24.8,32.4,29.2,5.0,32.4,...,0.0,NaN,0.0,0.0,15.0,8.5,1033.3,4.7,9.9,Clear
4,2016-01-07,Bronx,8407,New York City,46.3,31.3,38.8,37.2,12.3,34.0,...,0.0,NaN,0.0,0.0,11.9,6.3,1025.8,41.9,9.9,Partially cloudy

# Historical Traffic Data

In [ ]:
df_traffic = pd.read_csv("/content/Traffic_Volume_Counts_(Historical)_20260317.csv")

In [ ]:
df_traffic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6129 entries, 0 to 6128
Data columns (total 31 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ID             6129 non-null   int64
 1   SegmentID      6129 non-null   int64
 2   Roadway Name   6129 non-null   object
 3   From           6129 non-null   object
 4   To             6129 non-null   object
 5   Direction      6129 non-null   object
 6   Date           6129 non-null   object
 7   12:00-1:00 AM  6129 non-null   object
 8   1:00-2:00AM    6129 non-null   object
 9   2:00-3:00AM    6129 non-null   int64
 10  3:00-4:00AM    6129 non-null   int64
 11  4:00-5:00AM    6129 non-null   int64
 12  5:00-6:00AM    6129 non-null   object
 13  6:00-7:00AM    6129 non-null   object
 14  7:00-8:00AM    6129 non-null   object
 15  8:00-9:00AM    6129 non-null   object
 16  9:00-10:00AM   6129 non-null   object
 17  10:00-11:00AM  6129 non-null   object
 18  11:00-12:00PM  6129 non-null   object
 19  12:00-1:00PM   6129 non-null   object
 20  1:00-2:00PM    6129 non-null   object
 21  2:00-3:00PM    6129 non-null   object
 22  3:00-4:00PM    6129 non-null   object
 23  4:00-5:00PM    6129 non-null   object
 24  5:00-6:00PM    6129 non-null   object
 25  6:00-7:00PM    6129 non-null   object
 26  7:00-8:00PM    6129 non-null   object
 27  8:00-9:00PM    6129 non-null   object
 28  9:00-10:00PM   6129 non-null   object
 29  10:00-11:00PM  6129 non-null   object
 30  11:00-12:00AM  6129 non-null   object
dtypes: int64(5), object(26)
memory usage: 1.4+ MB

In [ ]:
hour_cols = df_traffic.columns[7:31]  # adjust slice to match your actual hour columns
df_traffic[hour_cols] = df_traffic[hour_cols].astype(str)
df_traffic[hour_cols] = df_traffic[hour_cols].apply(lambda x: x.str.replace(',', '', regex=False))
df_traffic[hour_cols] = df_traffic[hour_cols].apply(pd.to_numeric, errors='coerce')

In [ ]:
df_traffic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6129 entries, 0 to 6128
Data columns (total 31 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ID             6129 non-null   int64
 1   SegmentID      6129 non-null   int64
 2   Roadway Name   6129 non-null   object
 3   From           6129 non-null   object
 4   To             6129 non-null   object
 5   Direction      6129 non-null   object
 6   Date           6129 non-null   object
 7   12:00-1:00 AM  6129 non-null   int64
 8   1:00-2:00AM    6129 non-null   int64
 9   2:00-3:00AM    6129 non-null   int64
 10  3:00-4:00AM    6129 non-null   int64
 11  4:00-5:00AM    6129 non-null   int64
 12  5:00-6:00AM    6129 non-null   int64
 13  6:00-7:00AM    6129 non-null   int64
 14  7:00-8:00AM    6129 non-null   int64
 15  8:00-9:00AM    6129 non-null   int64
 16  9:00-10:00AM   6129 non-null   int64
 17  10:00-11:00AM  6129 non-null   int64
 18  11:00-12:00PM  6129 non-null   int64
 19  12:00-1:00PM   6129 non-null   int64
 20  1:00-2:00PM    6129 non-null   int64
 21  2:00-3:00PM    6129 non-null   int64
 22  3:00-4:00PM    6129 non-null   int64
 23  4:00-5:00PM    6129 non-null   int64
 24  5:00-6:00PM    6129 non-null   int64
 25  6:00-7:00PM    6129 non-null   int64
 26  7:00-8:00PM    6129 non-null   int64
 27  8:00-9:00PM    6129 non-null   int64
 28  9:00-10:00PM   6129 non-null   int64
 29  10:00-11:00PM  6129 non-null   int64
 30  11:00-12:00AM  6129 non-null   int64
dtypes: int64(26), object(5)
memory usage: 1.4+ MB

In [ ]:
df_traffic['total_volume'] = df_traffic[hour_cols].sum(axis=1)

In [ ]:
df_traffic.head()

,ID,SegmentID,Roadway Name,From,To,Direction,Date,12:00-1:00 AM,1:00-2:00AM,2:00-3:00AM,...,3:00-4:00PM,4:00-5:00PM,5:00-6:00PM,6:00-7:00PM,7:00-8:00PM,8:00-9:00PM,9:00-10:00PM,10:00-11:00PM,11:00-12:00AM,total_volume
0,100,8152,BRIELLE AVENUE,Suffolk Avenue,Livingston Avenue,EB,10/03/2020,19,33,30,...,163,136,123,133,119,80,56,40,29,1837
1,100,8152,BRIELLE AVENUE,Suffolk Avenue,Livingston Avenue,WB,10/03/2020,29,9,10,...,289,189,121,92,80,63,39,57,30,2833
2,102,147673,BROADWAY,Van Cortlandt Park South,West 242nd Street,SB,10/03/2020,120,102,56,...,451,434,413,426,347,268,211,199,166,6426
3,102,255653,BROADWAY,Broadway/ 7 Avenue Line,Broadway/ 7 Avenue Line,SB,10/03/2020,48,50,28,...,153,165,127,140,103,97,80,69,64,2418
4,102,158447,BROADWAY,West 242nd Street,Van Cortlandt Park South,NB,10/03/2020,189,146,100,...,701,662,604,551,485,442,342,293,269,9551

In [ ]:
df_daily = df_traffic.groupby('Date')['total_volume'].sum().reset_index()

In [ ]:
df_daily.head(64)

          Date  total_volume
0   05/01/2021        289141
1   05/02/2021        253376
2   05/03/2021        296893
3   05/04/2021        306985
4   05/05/2021        297450
..         ...           ...
59  12/09/2020          8426
60  12/10/2020          8536
61  12/11/2020          6647
62  12/12/2020          5496
63  12/13/2020          4455

[64 rows x 2 columns]